### ISSUE TITLE
[1.6] Random sector NPE on new game

### ISSUE THREAD

**Issue by Histidine91** [gomarz/SS-armaa#32]
```
187871 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException
java.lang.NullPointerException
	at data.scripts.world.systems.armaa_nekki.generate(armaa_nekki.java:56)
	at data.scripts.world.ARMAAWorldGen.generate(armaaworldgen.java:77)
	at data.scripts.MechaModPlugin.onNewGame(MechaModPlugin.java:68)
```

**Comment by gomarz** [comment]
NPE when looking for hybrasil, resolved and pushed to https://github.com/gomarz/SS-armaa/releases/tag/v1.6RC7
