### ISSUE TITLE
[1.95 pre-release] Altagrave (EX) causes a CTD

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#34]
285341 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException
java.lang.NullPointerException
	at com.fs.starfarer.combat.entities.Ship.<init>(Unknown Source)
	at com.fs.starfarer.loading.specs._.o00000(Unknown Source)
	at com.fs.starfarer.loading.specs._.o00000(Unknown Source)
	at com.fs.starfarer.loading.specs._.o00000(Unknown Source)
	at com.fs.starfarer.combat.systems.N.?00000(Unknown Source)
	at com.fs.starfarer.combat.systems.N.advanceImpl(Unknown Source)
	at com.fs.starfarer.combat.systems.F.advance(Unknown Source)
	at com.fs.starfarer.combat.entities.Ship.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by gomarz** [comment]
fix'd
