### ISSUE TITLE
[2.083] Docking AI Crash

### ISSUE THREAD

**Issue by DaMichel** [gomarz/SS-armaa#45]
Hi,

great mod. Thank you very much for it. It's one of my favorites. Unfortunately I come with a bug report. I've been playing a campaign for quite a while when suddenly the battles started crashing. It's well reproducible.

Here is a backtrace from the log file
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at data.scripts.ai.armaa_combat_docking_AI.init(armaa_combat_docking_ai.java:634)
	at data.hullmods.armaa_strikeCraft.checkRefitStatus(armaa_strikeCraft.java:677)
	at data.hullmods.armaa_strikeCraft.advanceInCombat(armaa_strikeCraft.java:815)
	at com.fs.starfarer.combat.entities.Ship.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

I looked up the line in `armaa_combat_docking_AI.init`. The line info does not seem to be super accurate. Below on line `639` however, I found
```java
						bayNo = i;
						if(bayNo > potentialCarrier.getLaunchBaysCopy().size())
							continue;
```
Shouln't that be `>=`?

Anyway, would be great if you could take a look at that.

[starsector.log.zip](https://github.com/gomarz/SS-armaa/files/9077980/starsector.log.zip)

I can send you the savegame as well.

Best regards

**Comment by gomarz** [comment]
Hi, thanks for your feedback!

I just released a new update (Version 2.083) which may have fixed this bug. Can you try with that version and see if the issue persists?

**Comment by DaMichel** [comment]
Looks like it did fix it. Thank you very much.

**Comment by DaMichel** [comment]
Oh, no, wait a sec. It's back. Now looking at the correct source, hopefully, the backtrace confirms my suspicion.
```
5929650 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at data.scripts.ai.armaa_combat_docking_AI.init(armaa_combat_docking_ai.java:643)
	at data.hullmods.armaa_strikeCraft.checkRefitStatus(armaa_strikeCraft.java:696)
	at data.hullmods.armaa_strikeCraft.advanceInCombat(armaa_strikeCraft.java:834)
	at com.fs.starfarer.combat.entities.Ship.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
Which points to this line
```java
						fighter = potentialCarrier.getLaunchBaysCopy().get(bayNo).getWing().getLeader();
```
Lord knows why the launch-bay array is smaller than `potentialCarrier.getNumFighterBays()`. But you seem to have encountered strange issues before ... ;-)

**Comment by gomarz** [comment]
I suspect its exactly the reason you mentioned previously, so I altered the code to check 
`if(bayNo >= potentialCarrier.getLaunchBaysCopy().size())`
Hopefully this resolves it!

**Comment by DaMichel** [comment]
Thanks again. I "tested" it a bit and no more crashes. 👍
