### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by superyuuki** [gomarz/SS-armaa#54]
Getting this exception randomly when my armaa mech undocks from a hangar

`2558501 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException
java.lang.NullPointerException
	at data.scripts.ai.armaa_combat_docking_AI.takeOff(armaa_combat_docking_ai.java:484)
	at data.scripts.ai.armaa_combat_docking_AI.advance(armaa_combat_docking_ai.java:238)
	at com.fs.starfarer.combat.entities.Ship$ShipAIWrapper.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
`

Also getting a ton of spam about

`2286334 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing alpha to  remainder: skyMindBeta isSame?: false
2286334 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing alpha to  remainder: skyMindGamma isSame?: false
2286334 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing beta to  remainder: skyMindAlpha isSame?: false
2286334 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing beta to  remainder: skyMindBeta isSame?: true
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing beta to  remainder: skyMindGamma isSame?: false
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing gamma to  remainder: skyMindAlpha isSame?: false
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing gamma to  remainder: skyMindBeta isSame?: false
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing gamma to  remainder: skyMindGamma isSame?: true
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing alpha to  remainder: skyMindAlpha isSame?: true
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing alpha to  remainder: skyMindBeta isSame?: false
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing alpha to  remainder: skyMindGamma isSame?: false
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing beta to  remainder: skyMindAlpha isSame?: false
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing beta to  remainder: skyMindBeta isSame?: true
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing beta to  remainder: skyMindGamma isSame?: false
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing gamma to  remainder: skyMindAlpha isSame?: false
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing gamma to  remainder: skyMindBeta isSame?: false
2286335 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing gamma to  remainder: skyMindGamma isSame?: true
2286352 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing alpha to  remainder: skyMindAlpha isSame?: true
2286353 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing alpha to  remainder: skyMindBeta isSame?: false
2286353 [Thread-3] INFO  data.hullmods.armaa_aicoreutilityscript  - Comparing alpha to  remainder: skyMindGamma isSame?: false`

**Comment by gomarz** [comment]
Thanks for the report! I think this is fixed in dev branch, you can try replacing the .jar from current version to it(https://github.com/gomarz/SS-armaa/blob/dev/jars/armaa.jar) and it should work. Just swapping to dev branch might work as well but it might be unstable

**Comment by superyuuki** [comment]
Updated the jar, running into a new issue which is making it impossible to even load the save.

`210313 [Thread-3] ERROR com.fs.starfarer.campaign.save.CampaignGameManager  - Failed calling method
---- Debugging information ----
message             : Failed calling method
cause-exception     : java.lang.NullPointerException
cause-message       : null
method              : com.fs.starfarer.campaign.fleet.FleetMember.readResolve()
class               : com.fs.starfarer.campaign.fleet.FleetMember
required-type       : com.fs.starfarer.campaign.fleet.FleetMember
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
line number         : 504730
class[1]            : java.lang.ref.WeakReference
class[2]            : com.fs.starfarer.api.impl.campaign.plog.SModRecord
class[3]            : java.util.ArrayList
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[4]            : com.fs.starfarer.api.impl.campaign.plog.PlaythroughLog
class[5]            : java.util.LinkedHashMap
converter-type[2]   : com.thoughtworks.xstream.converters.collections.MapConverter
class[6]            : com.fs.starfarer.campaign.rules.Memory
class[7]            : com.fs.starfarer.api.impl.campaign.missions.hub.BaseHubMission$VariableSet
class[8]            : exerelin.campaign.intel.missions.remnant.RemnantM1
class[9]            : com.fs.starfarer.api.impl.campaign.missions.hub.MissionFleetAutoDespawn
class[10]           : com.fs.starfarer.campaign.fleet.CampaignFleet
class[11]           : com.fs.util.container.repo.ObjectRepository
class[12]           : com.fs.starfarer.campaign.StarSystem
class[13]           : com.fs.starfarer.campaign.CampaignPlanet
class[14]           : com.fs.starfarer.campaign.CircularOrbit
class[15]           : com.fs.starfarer.campaign.econ.Market
class[16]           : com.fs.starfarer.api.impl.campaign.fleets.RouteManager$RouteData
class[17]           : com.fs.starfarer.api.impl.campaign.fleets.RouteManager
class[18]           : com.fs.starfarer.campaign.econ.reach.ReachEconomy
class[19]           : com.fs.starfarer.campaign.econ.reach.ReachEconomyStepper
class[20]           : com.fs.starfarer.campaign.econ.Economy
class[21]           : com.fs.starfarer.campaign.CustomCampaignEntity
class[22]           : com.fs.starfarer.campaign.StarSystem$UpdateFromHyperspaceLocation
class[23]           : com.fs.starfarer.campaign.BaseLocation$LocationToken
class[24]           : com.fs.starfarer.campaign.Hyperspace
class[25]           : com.fs.starfarer.campaign.CampaignEngine
converter-type[3]   : com.fs.starfarer.campaign.save.oooO
version             : not available
-------------------------------
com.thoughtworks.xstream.converters.ConversionException: Failed calling method
---- Debugging information ----
message             : Failed calling method
cause-exception     : java.lang.NullPointerException
cause-message       : null
method              : com.fs.starfarer.campaign.fleet.FleetMember.readResolve()
class               : com.fs.starfarer.campaign.fleet.FleetMember
required-type       : com.fs.starfarer.campaign.fleet.FleetMember
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
line number         : 504730
class[1]            : java.lang.ref.WeakReference
class[2]            : com.fs.starfarer.api.impl.campaign.plog.SModRecord
class[3]            : java.util.ArrayList
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[4]            : com.fs.starfarer.api.impl.campaign.plog.PlaythroughLog
class[5]            : java.util.LinkedHashMap
converter-type[2]   : com.thoughtworks.xstream.converters.collections.MapConverter
class[6]            : com.fs.starfarer.campaign.rules.Memory
class[7]            : com.fs.starfarer.api.impl.campaign.missions.hub.BaseHubMission$VariableSet
class[8]            : exerelin.campaign.intel.missions.remnant.RemnantM1
class[9]            : com.fs.starfarer.api.impl.campaign.missions.hub.MissionFleetAutoDespawn
class[10]           : com.fs.starfarer.campaign.fleet.CampaignFleet
class[11]           : com.fs.util.container.repo.ObjectRepository
class[12]           : com.fs.starfarer.campaign.StarSystem
class[13]           : com.fs.starfarer.campaign.CampaignPlanet
class[14]           : com.fs.starfarer.campaign.CircularOrbit
class[15]           : com.fs.starfarer.campaign.econ.Market
class[16]           : com.fs.starfarer.api.impl.campaign.fleets.RouteManager$RouteData
class[17]           : com.fs.starfarer.api.impl.campaign.fleets.RouteManager
class[18]           : com.fs.starfarer.campaign.econ.reach.ReachEconomy
class[19]           : com.fs.starfarer.campaign.econ.reach.ReachEconomyStepper
class[20]           : com.fs.starfarer.campaign.econ.Economy
class[21]           : com.fs.starfarer.campaign.CustomCampaignEntity
class[22]           : com.fs.starfarer.campaign.StarSystem$UpdateFromHyperspaceLocation
class[23]           : com.fs.starfarer.campaign.BaseLocation$LocationToken
class[24]           : com.fs.starfarer.campaign.Hyperspace
class[25]           : com.fs.starfarer.campaign.CampaignEngine
converter-type[3]   : com.fs.starfarer.campaign.save.oooO
version             : not available
-------------------------------
	at com.thoughtworks.xstream.core.util.SerializationMembers.callReadResolve(SerializationMembers.java:82)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:282)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:73)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:98)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:91)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:85)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:80)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:73)
	at com.thoughtworks.xstream.converters.collections.MapConverter.putCurrentEntryIntoMap(MapConverter.java:110)
	at com.thoughtworks.xstream.converters.collections.MapConverter.populateMap(MapConverter.java:98)
	at com.thoughtworks.xstream.converters.collections.MapConverter.populateMap(MapConverter.java:92)
	at com.thoughtworks.xstream.converters.collections.MapConverter.unmarshal(MapConverter.java:87)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)`
	
`Caused by: java.lang.NullPointerException
	at data.hullmods.armaa_skyMindSuiteBeta.advanceInCampaign(armaa_skyMindSuiteBeta.java:238)
	at com.fs.starfarer.campaign.fleet.FleetData.syncIfNeeded(Unknown Source)
	at com.fs.starfarer.campaign.fleet.FleetData.getMembers(Unknown Source)
	at com.fs.starfarer.campaign.fleet.FleetData.getMembersListCopy(Unknown Source)
	at com.fs.starfarer.api.impl.campaign.skills.BaseSkillEffectDescription.getNumFighterBays(BaseSkillEffectDescription.java:752)
	at com.fs.starfarer.api.impl.campaign.skills.BaseSkillEffectDescription.computeAndCacheThresholdBonus(BaseSkillEffectDescription.java:314)
	at com.fs.starfarer.api.impl.campaign.skills.BaseSkillEffectDescription.computeAndCacheThresholdBonus(BaseSkillEffectDescription.java:297)
	at com.fs.starfarer.api.impl.campaign.skills.CarrierGroup$Level1.apply(CarrierGroup.java:41)
	at com.fs.starfarer.campaign.CharacterStats.applyFleetwideToStats(Unknown Source)
	at com.fs.starfarer.campaign.fleet.FleetMember.updateStats(Unknown Source)
	at com.fs.starfarer.campaign.fleet.FleetMember.readResolve(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.xstream.core.util.SerializationMembers.callReadResolve(SerializationMembers.java:78)
	... 333 more`
	
	issues seem most related to the AI Core

**Comment by superyuuki** [comment]
not sure what happened to the formatting above but should still be clear enough to understand

**Comment by gomarz** [comment]
Misc.getAICoreOfficerPlugin(ITEM) can apparently resolve to null, I just pushed an update - new jar should resolve hopefully

**Comment by superyuuki** [comment]
hate to be the bearer of bad news but things are still exploding.
if it's any consolation it may be Combat Chatter's fault here

`9103872 [Thread-3] INFO  org.histidine.chatter.combat.ChatterCombatPlugin  - Adding ship Gridfire One, isEnemy 0
9103872 [Thread-3] INFO  org.histidine.chatter.combat.ChatterCombatPlugin  - Adding ship Aleph One, isEnemy 0
9104870 [Thread-3] INFO  org.histidine.chatter.combat.ChatterCombatPlugin  - Adding ship null, isEnemy 0
9193332 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException
java.lang.NullPointerException
	at data.scripts.ai.armaa_combat_docking_AI.init(armaa_combat_docking_AI.java:594)
	at data.hullmods.armaa_strikeCraft.checkRefitStatus(armaa_strikeCraft.java:745)
	at data.hullmods.armaa_strikeCraft.advanceInCombat(armaa_strikeCraft.java:886)
	at com.fs.starfarer.combat.entities.Ship.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by gomarz** [comment]
Do you happen to know what ship was being landed on?
I've seen this pop up a few times, but never experienced it myself.  my suspicion is its related to a ship with no defined launch bays, but im not 100% sure

Anyway, here's another jar from the dev branch https://github.com/gomarz/SS-armaa/raw/dev/jars/armaa.jar

**Comment by superyuuki** [comment]
I tried to dock on a ship with 2 bays, each bay holding an in-built wing. Maybe that's the cause?
