### ISSUE TITLE
Game crashes when fighting pirates

### ISSUE THREAD

**Issue by specopsbarton** [gomarz/SS-armaa#64]
Hello, I'm posting here because I got similar error like in fractal forum of your mod arma armatura - 

https://fractalsoftworks.com/forum/index.php?topic=18751.1605

517638 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.ClassCastException: class com.fs.starfarer.combat.entities.Ship cannot be cast to class org.lwjgl.util.vector.Vector2f (com.fs.starfarer.combat.entities.Ship and org.lwjgl.util.vector.Vector2f are in unnamed module of loader 'app')
java.lang.ClassCastException: class com.fs.starfarer.combat.entities.Ship cannot be cast to class org.lwjgl.util.vector.Vector2f (com.fs.starfarer.combat.entities.Ship and org.lwjgl.util.vector.Vector2f are in unnamed module of loader 'app')
	at com.fs.starfarer.combat.ai.system.a.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.ai.BasicShipAI.advance(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatState.traverse(Unknown Source) ~[port_obf.jar:?]
	at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
	
This crash happens when I fight pirates, which all use takeshido ships (mod epta consortium). If you need anything more to know just ask.

Here is starsector.log from discord, where I tried to get help from people of mod epta consortium, but they couldn't help me :(

https://cdn.discordapp.com/attachments/908453692271886418/1263146774068068493/starsector.log?ex=66992c9b&is=6697db1b&hm=1b6c5de2e5eb88772a29eafdc96d69aab80129eff9e622430b9d781a8bb23073&

starsector 0.97a-RC11, java jdk-23+7

**Comment by gomarz** [comment]
What ships were you using?

**Comment by specopsbarton** [comment]
Only one gundam dolos - but this crash only happened while fighting pirates, I already fought for example hegemony and there were no crash.

**Comment by specopsbarton** [comment]
So any way to fix this?

**Comment by gomarz** [comment]
don't know root cause and never repro'd, probaby caused by fenris teleporting something while system is active?
Should be stopped since we forcibly kill the system before teleporting
